### ISSUE TITLE
Encrypt: could not get implementation

### ISSUE THREAD

**Issue by mukeshtiwari** [rmculpepper/crypto#1]
I am working on problem 7 of cryptopals [1], but I am getting could not get implementation. 

```
> (define key (generate-cipher-key '(aes ecb)))
>  (define iv (generate-cipher-iv '(aes ecb)))
> key
#"\321h8~FO\203\3478\273\264\337\317=W\345"
> iv
#""
> (define ciphertext (encrypt '(aes ecb) key iv "Hello world!"))
. . encrypt: could not get implementation
  cipher: '(aes ecb)
```

[1] https://cryptopals.com/sets/1/challenges/7

**Comment by rmculpepper** [comment]
Did you set `(crypto-factories)`?

If not, does it work if you do the following first:

    (require crypto/all)
    (use-all-factories!)

**Comment by mukeshtiwari** [comment]
@rmculpepper  Thank you very much for help.

**Comment by rmculpepper** [comment]
@jsmith037982374 You choose the factories first, based on what libraries you have on your system or what libraries you expect to have wherever you intend to deploy your program. For example, if you choose to rely on libcrypto, you would configure the factories like this:

    (require crypto crypto/libcrypto)
    (crypto-factories (list libcrypto-factory))

If you want to see what factories have an implementation of `'(aes ctr)`, you can do this:

    (require crypto crypto/all)
    (filter (lambda (f) (get-cipher '(aes ctr) f)) all-factories)

Did that answer your question?

**Comment by jsmith037982374** [comment]
@rmculpepper yes, that makes a lot more sense now! Out of curiosity, where would I be able to look at the code that calls the foreign libraries?

Thanks!

**Comment by rmculpepper** [comment]
Each provider has a subdirectory in crypto-lib/private/ for all of the provider-specific code, and each directory has a standard layout: ffi.rkt defines the constants and foreign functions; {digest.rkt, cipher.rkt, etc} use those foreign functions to implement this library's high-level API; and factory.rkt makes the high-level pieces available using the factory lookup methods.

All of the provider-specific code also depends heavily on the interfaces, base classes, and other utilities implemented in crypto-lib/private/common/. See the NOTES.md file in that directory for an overview.

**Comment by jsmith037982374** [comment]
@rmculpepper thank you!
