### ISSUE TITLE
/usr/lib/libnettle.so: undefined symbol: nettle_hashes

### ISSUE THREAD

**Issue by hashimmm** [rmculpepper/crypto#10]
I have version 3.5.1-2 of the nettle library on manjaro linux. I'm running Racket CS v7.5. I get this error when trying to run an application that uses racket/crypto
```
/home/pltbuild/build/plt-cs-release/bundle/racket/share/pkgs/drracket/drracket/private/stack-checkpoint.rkt:40:30: ffi-obj: could not find export from foreign library
  name: nettle_hashes
  library: libnettle.so
  system error: /usr/lib/libnettle.so: undefined symbol: nettle_hashes
```

Looking up symbols in libnettle.so gets me this:
```
$ nm -gD /usr/lib/libnettle.so | grep hashes
0000000000018bc0 T nettle_get_hashes
0000000000038360 D _nettle_hashes
```

**Comment by hashimmm** [comment]
The docs explicitly mention that libnettle.so.6 is required, and I have libnettle.so.7
I suppose I should close this?

**Comment by hashimmm** [comment]
If I change to use libcrypto, I get this when running a program (which has a file named resource-routes.rkt):

`resource-routes.rkt:49:2: invalid memory reference.  Some debugging context lost`

I'm now using Racket CS 7.6

**Comment by rmculpepper** [comment]
Thanks for the reports! I've pushed an update to make the crypto library work with Nettle 3.5 and later. I had already done the work but hadn't gotten around to pushing it yet.

Regarding the crash when using libcrypto: That looks like a memory corruption error. Racket CS places slightly different requirements on uses of the FFI, and I probably missed something when I was updating this library to work with Racket CS. Does your program reliably cause that error? Does it always crash at about the same point (like the same operation), or does that vary? If you have a small test program that causes the error that you could send me, that would be ideal, but if not anything that narrows down the possible sources of the bug would be helpful. I'll try to take a look at this within the next day or so.

**Comment by hashimmm** [comment]
Thanks! I'm able to reliably get the memory error but it doesn't seem to have anything to do with the crypto library. So this issue is resolved, I suppose. (I didn't verify your changes, for the time being I've just switched to libcrypto.)

**Comment by rmculpepper** [comment]
Okay, thanks. I'll close this issue, then.
