### ISSUE TITLE
Fails to get-kdf on current Racket CS

### ISSUE THREAD

**Issue by vkz** [rmculpepper/crypto#11]
Hy Ryan.

I've been having trouble getting the password hashing to work with Racket CS built from the current master. Here's what I'm seeing on Racket v7.7.0.4 [cs] with libargon2 installed from Bogdan's https://github.com/Bogdanp/racket-libargon2

```racket
#lang racket

(require crypto
         crypto/argon2)

#;(parameterize ((crypto-factories (list argon2-factory)))
    (pwhash 'argon2id #"mypassword" '((t 1000) (m 4096) (p 1))))

;; =>

; pwhash: could not get implementation
;   KDF: 'argon2id
; Context:
;  .../crypto-lib/main.rkt:460:0 pwhash
;  .../private/arrow-val-first.rkt:489:18


(get-kdf 'argon2id (list argon2-factory))

;; =>

#f

;; Do factories hide their identity or does this mean object sets itself to #f at some point?
(object-info argon2-factory)
#f
#t

(require setup/dirs)
(get-lib-search-dirs)

;; =>

'(#<path:/Users/russki/Library/Racket/development/lib>
  #<path:/Users/russki/Code/racket-cs/racket/lib>)
```

Dylib appears where it needs to be:
```
~/Code/racket-cs/racket/lib $ nm -gU libargon2.dylib
0000000000009080 D _FLAG_clear_internal_memory
0000000000002380 T _allocate_memory
0000000000000db0 T _argon2_ctx
0000000000001b60 T _argon2_encodedlen
0000000000001b30 T _argon2_error_message
0000000000000e70 T _argon2_hash
0000000000005910 T _argon2_thread_create
0000000000005950 T _argon2_thread_exit
0000000000005940 T _argon2_thread_join
0000000000000d50 T _argon2_type2string
00000000000011f0 T _argon2_verify
0000000000001490 T _argon2_verify_ctx
0000000000001650 T _argon2d_ctx
00000000000010d0 T _argon2d_hash_encoded
0000000000001120 T _argon2d_hash_raw
0000000000001630 T _argon2d_verify
0000000000001680 T _argon2d_verify_ctx
0000000000001660 T _argon2i_ctx
0000000000001040 T _argon2i_hash_encoded
0000000000001090 T _argon2i_hash_raw
0000000000001620 T _argon2i_verify
0000000000001810 T _argon2i_verify_ctx
0000000000001670 T _argon2id_ctx
0000000000001160 T _argon2id_hash_encoded
00000000000011b0 T _argon2id_hash_raw
0000000000001640 T _argon2id_verify
00000000000019a0 T _argon2id_verify_ctx
0000000000006a30 T _b64len
0000000000005150 T _blake2b
0000000000005000 T _blake2b_final
0000000000004530 T _blake2b_init
0000000000004640 T _blake2b_init_key
0000000000004430 T _blake2b_init_param
0000000000005300 T _blake2b_long
0000000000004850 T _blake2b_update
0000000000002460 T _clear_internal_memory
0000000000001c20 T _copy_block
0000000000005960 T _decode_string
0000000000006100 T _encode_string
0000000000003650 T _fill_first_blocks
0000000000002f30 T _fill_memory_blocks
0000000000006ab0 T _fill_segment
00000000000024b0 T _finalize
0000000000002400 T _free_memory
0000000000002e80 T _index_alpha
0000000000001c10 T _init_block_value
00000000000040d0 T _initial_hash
0000000000004310 T _initialize
0000000000006a70 T _numlen
0000000000002480 T _secure_wipe_memory
0000000000003500 T _validate_inputs
0000000000001c30 T _xor_block
```

Related issue https://github.com/Bogdanp/koyo/issues/18

**Comment by rmculpepper** [comment]
Thanks for the report! Could you also try the following:
- Start racket using `racket -W "debug@ffi-lib"`. It should log several lines of output; you can ignore them.
- Run `(require crypto crypto/argon2)`. What output gets logged after this command?
- Run `(factory-print-info argon2-factory)`. What does it print?

Regarding `object-info`, objects are non-inspectable by default, like structs. The `#f` just means inspection failed, not that the object itself is `#f` or invalid.

**Comment by vkz** [comment]
```
~/Code/racket-cs/racket/lib $ racket -W "debug@ffi-lib"
Welcome to Racket v7.7.0.4 [cs].
> (require crypto crypto/argon2)
ffi-lib: failed for (ffi-lib "libargon2" '("1" "0" #f)), tried: 
  #<path:/Users/russki/Library/Racket/development-cs/lib/libargon2.1.dylib> (no such file)
  #<path:/Users/russki/Library/Racket/development-cs/lib/libargon2.0.dylib> (no such file)
  #<path:/Users/russki/Library/Racket/development-cs/lib/libargon2.dylib> (no such file)
  #<path:/Users/russki/Library/Racket/development-cs/lib/libargon2> (no such file)
  #<path:/Users/russki/Code/racket-cs/racket/lib/libargon2.1.dylib> (no such file)
  #<path:/Users/russki/Code/racket-cs/racket/lib/libargon2.0.dylib> (no such file)
  #<path:/Users/russki/Code/racket-cs/racket/lib/libargon2.dylib> (exists)
  #<path:/Users/russki/Code/racket-cs/racket/lib/libargon2> (no such file)
  "libargon2.1.dylib" (using OS library search path)
  "libargon2.0.dylib" (using OS library search path)
  "libargon2.dylib" (using OS library search path)
  "libargon2" (using OS library search path)
  #<path:/Users/russki/Code/racket-cs/racket/lib/libargon2.1.dylib> (no such file)
  #<path:/Users/russki/Code/racket-cs/racket/lib/libargon2.0.dylib> (no such file)
  #<path:/Users/russki/Code/racket-cs/racket/lib/libargon2.dylib> (exists)
  #<path:/Users/russki/Code/racket-cs/racket/lib/libargon2> (no such file)
> (factory-print-info argon2-factory)
Library info:
 version: #f
> 
```

It does report that in one location the lib exists, why does it report ffi-lib failure though?

**Comment by rmculpepper** [comment]
Thanks. That line means that the file exists but the OS-level `dlopen` call failed. That's usually due to an unsatisfied library dependency or a missing symbol.

I tried installing the Racket `libargon2` package on my Mac. If I run

    (require ffi/unsafe)
    (ffi-lib "/PATH/TO/THAT/libargon2.dylib")

I get an error including the lines

    system error: dlopen(/PATH/TO/libargon2.dylib, 6): Symbol not found: ____chkstk_darwin
    Referenced from: /PATH/TO/libargon2.dylib
    Expected in: /usr/lib/libSystem.B.dylib

Do you get the same error? If so, possibly there's a problem with the dylib file, or possibly it was compiled against a newer Mac OS SDK and we have older versions of Mac OS. (Mine is 10.12.6, which is quite old at this point.)

Also, if I run `otool -L /PATH/TO/libargon2.dylib` the first line is

    @rpath/libargon2.1.dylib (....)

which also looks suspicious, but I'm not fluent enough in `otool -L` output to be sure. (Maybe the first line is the identity of the library, and the remaining lines are the dependencies?)

FWIW, the version installed by homebrew (`brew install argon2`, IIRC) works for me.

**Comment by Bogdanp** [comment]
> possibly it was compiled against a newer Mac OS SDK and we have older versions of Mac OS.

The library was [built on](https://github.com/Bogdanp/racket-libargon2/blob/2120f58459ee4f07a4efc07a65ef508d88ec46c2/.github/workflows/push.yml#L17) macOS 10.14 (against the 10.14 SDK, using Xcode 10.30) so that could definitely be it.

**Comment by rmculpepper** [comment]
From the documentation I found, it seems that github no longer admits the existence of 10.14 build machines, but the [docs for the 10.15 build machines](https://github.com/actions/virtual-environments/blob/master/images/macos/macos-10.15-Readme.md) say that SDK 10.14 is the oldest available. So there doesn't seem to be an easy fix. Might be good to add compatibility notes to the libargon2 pkg readme.

**Comment by vkz** [comment]
```
cr.rkt> (require ffi/unsafe)
cr.rkt> (ffi-lib "/Users/russki/Code/racket-cs/racket/lib/libargon2.dylib")
; ffi-lib: could not load foreign library
;   path: /Users/russki/Code/racket-cs/racket/lib/libargon2.dylib
;   system error: dlopen(/Users/russki/Code/racket-cs/racket/lib/libargon2.dylib, 6): Symbol not found: ____chkstk_darwin
;   Referenced from: /Users/russki/Code/racket-cs/racket/lib/libargon2.dylib (which was built for Mac OS X 10.15)
;   Expected in: /usr/lib/libSystem.B.dylib
;  in /Users/russki/Code/racket-cs/racket/lib/libargon2.dylib
; Context:
;  .../ffi/unsafe.rkt:131:0 body of "/Users/russki/Code/temp/cr.rkt"
;  .../racket/repl.rkt:11:26
```

it does look like it was built for smth newer. I'm on 10.13

**Comment by rmculpepper** [comment]
Great, glad it's working. I'll close this issue. I've also pushed a change to that makes `factory-print-info` print the load error, if one occurred.
