### ISSUE TITLE
New Function Names in OpenSSL 3

### ISSUE THREAD

**Issue by evdubs** [rmculpepper/crypto#20]
Hi,

The Linux distribution I use (Ubuntu 22.04) recently migrated to using OpenSSL 3. OpenSSL 3 has some API/ABI changes. In particular, 

```
EVP_MD_size -> EVP_MD_get_size
EVP_MD_block_size -> EVP_MD_get_block_size
```

in `ffi.rkt` and `digest.rkt` needed to be added/changed for the library to work for me. Is there a way to incorporate these new function names as a fall back in case the original functions aren't found?

**Comment by evdubs** [comment]
Link to man pages: https://www.openssl.org/docs/man3.0/man3/EVP_MD_size.html

**Comment by rmculpepper** [comment]
Basic support for OpenSSL 3 is merged now.
