### ISSUE TITLE
generate-private-key: could not get implementation

### ISSUE THREAD

**Issue by jaromirmuller** [rmculpepper/crypto#6]
When I run 
```
(require crypto crypto/sodium racket/match)
(crypto-factories sodium-factory)
(define alice:privkey (generate-private-key 'ecx '((curve x25519))))
```

then on my macosx I get error:

```
generate-private-key: could not get implementation
  algorithm: 'ecx
```

I have no idea what is wrong.

I my ubuntu machine it works fine.

Thank you for any help.

**Comment by rmculpepper** [comment]
It sounds like Racket cannot find the libsodium foreign library. Where is libsodium installed on your Mac?
